# Generated by Django 4.2.5 on 2023-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='img',
            field=models.ImageField(default='media/sale.jpg', upload_to=''),
        ),
    ]
